//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAO_CAO_DOANH_THU
    {
        public int STT { get; set; }
        public string MaSach { get; set; }
        public int GiaNhap { get; set; }
        public int GiaBan { get; set; }
        public int SoLuongBan { get; set; }
        public Nullable<int> DoanhThu { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual SACH SACH { get; set; }
    }
}
