//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANH_SO_BAN_HANG
    {
        public int STT { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<int> DoanhSoBan { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
