//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        public KHACH_HANG()
        {
            this.HOA_DON_BAN = new HashSet<HOA_DON_BAN>();
        }
    
        public string SDT { get; set; }
        public string HoTen { get; set; }
    
        public virtual ICollection<HOA_DON_BAN> HOA_DON_BAN { get; set; }
    }
}
