//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_SACH
    {
        public LOAI_SACH()
        {
            this.SACHes = new HashSet<SACH>();
        }
    
        public string MaLoaiSach { get; set; }
        public string TenLoaiSach { get; set; }
    
        public virtual ICollection<SACH> SACHes { get; set; }

        public override string ToString()
        {
            return TenLoaiSach;
        }
    }
}
