//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyEntities : DbContext
    {
        public QuanLyEntities()
            : base("name=QuanLyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BAO_CAO_DOANH_THU> BAO_CAO_DOANH_THU { get; set; }
        public DbSet<CHI_TIET_HOA_DON_BAN> CHI_TIET_HOA_DON_BAN { get; set; }
        public DbSet<CHI_TIET_HOA_DON_NHAP> CHI_TIET_HOA_DON_NHAP { get; set; }
        public DbSet<DOANH_SO_BAN_HANG> DOANH_SO_BAN_HANG { get; set; }
        public DbSet<HOA_DON_BAN> HOA_DON_BAN { get; set; }
        public DbSet<HOA_DON_NHAP> HOA_DON_NHAP { get; set; }
        public DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public DbSet<LOAI_SACH> LOAI_SACH { get; set; }
        public DbSet<NHA_XUAT_BAN> NHA_XUAT_BAN { get; set; }
        public DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public DbSet<SACH> SACHes { get; set; }
        public DbSet<TK_NHANVIEN> TK_NHANVIEN { get; set; }
    }
}
