//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN
    {
        public NHAN_VIEN()
        {
            this.DOANH_SO_BAN_HANG = new HashSet<DOANH_SO_BAN_HANG>();
            this.HOA_DON_BAN = new HashSet<HOA_DON_BAN>();
        }
    
        public string MaNhanVien { get; set; }
        public string HoTen { get; set; }
        public string DanToc { get; set; }
        public string GioiTinh { get; set; }
        public string CMND { get; set; }
        public string SoDienThoai { get; set; }
        public string QueQuan { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public bool TrangThai { get; set; }
        public bool isAdmin { get; set; }
    
        public virtual ICollection<DOANH_SO_BAN_HANG> DOANH_SO_BAN_HANG { get; set; }
        public virtual ICollection<HOA_DON_BAN> HOA_DON_BAN { get; set; }
        public virtual TK_NHANVIEN TK_NHANVIEN { get; set; }
    }
}
